# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f089cb62cdca0340a2b48fccf9b7f4fe3d390ec30c737024f947b5554a5046a9c69a6caa6f9323698a5baf1d69688937feb02a621e22ab4b2e1e549d2a865445

test:
  secret_key_base: 42d037f3f54992ebdf4fc66769e436c78cb9a3b6c4e584108a3b74e64aa1ba6f0954d0f6da9ac1a5a2004da218f85c42b683aefe0926e4cdcca88660341287b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
